### ISSUE TITLE
some thoughts on onchain masternodes

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dips#11]
first of all since I started with masternode code I was actually going to do this but after talking to UdjinM6 realized the plan was to go with onchain so its great we follow the same ideologies about how this will work.

A few questions.

1) since you split the keys can you not store the base58 address for collateral instead of pubkey so that you can support p2sh collateral contracts? Any thoughts on using schnorr here?

2) is the ip check that it is unique across the mn list a strict requirement? doing so removes plausible deniability of operation of a masternode through historical context. I would think only keys and sigs only need to be onchain to make deterministic masternode services work properly and a proof on chain can exist to make the rest of the data immutable.

3) you might want a notion or identity connected to masternodes to build these offchain anchor and aux services connected to your mn object. You can then prune based on identity liveness (expiry) like I did with Syscoin. This makes the architecture pretty flexible. Although most of that can be done offchain aswell through a merkle tree abstraction where root hash is stored on chain to enable enterprise grade DApps function offchain but store data through the dashdrive. To me data liveness matterd little as data is cheap and cloud uptime is good enough. IPFS is sufficient as a content addressable storage medium is all thats needed and not incentivised storage. You store what you care about and pay others if needed through cloud type services.

**Comment by PaulieD** [comment]
These are really interesting points, @thephez do you have any thoughts?

**Comment by thephez** [comment]
@sidhujag Regarding item 2 - It does not seem that removing the IP would improve plausible deniability much. Every node on the network already knows the details for every MN today (and could log it trivially). For a MN to serve its intended purpose, it must be publicly accessible so its IP must be resolvable somehow. Including it on-chain relieved the issue of each node having to [maintain its own list independently](https://github.com/dashpay/dips/blob/master/dip-0003.md#motivation-and-previous-system) (which could lead to discrepancies between nodes).

**Comment by sidhujag** [comment]
The nodes remove stale data so you don't have forward secrecy if you move onchain. In p2p context your not historically logging and keeping every masternode throughout the start of time. its a big difference and might mean something legally for MNO going fwd. It is a valid thought hence I put that up there but idk if it really means anything if your not doing anything wrong (is privacy illegal in blockchains? not yet anyway)
