### ISSUE TITLE
DIP-3 Operator Key (BLS)

### ISSUE THREAD

**Issue by thephez** [dashpay/dips#23]
DIP-3 needs to be updated with details regarding the Operator key being changed to BLS.

- [x] Update ProRegTx description with operator BLS key details
- [x] Remove ProUpServTx payloadSigSize field for BLS signatures (BLS sigs are 96 bytes)
- [x] Remove ProUpRevTx payloadSigSize field for BLS signatures (BLS sigs are 96 bytes)

**Comment by codablock** [comment]
See https://github.com/dashpay/dips/pull/25
