### ISSUE TITLE
versions in special transactions chart seem wrong

### ISSUE THREAD

**Issue by taw00** [dashpay/dips#35]
https://github.com/dashpay/dips/blob/master/dip-0002-special-transactions.md

In dip-0002, it is mentioned that the version field will be set to >=3 to identify special transactions and that right now for normal transactions, they are version 2? I think. The document is rather clear, until it isn't. If that is the case, the special transaction chart (see URL above) has all versions incorrectly set to  1. I don't grok this... or there is an error. Or both. :) -t0dd

**Comment by QuantumExplorer** [comment]
There are 2 version fields, one is the version field of the transaction, which is >= 3 if a special transaction, the other is the version field of the special transaction and is in the special transaction payload. The document you linked is referring to the latter.

**Comment by taw00** [comment]
Okay. Then there is a clarity issue, IMHO, versus an actual error. Maybe the DIP can be massaged a bit?

**Comment by thephez** [comment]
@taw00 Would changing the column heading in the table to `Payload Version` clear it up?

**Comment by taw00** [comment]
> @taw00 Would changing the column heading in the table to `Payload Version` clear it up?

Yes. :)

Actually, I don't know. It's been nearly 4 years since I posted this. But, yeah, I think that would add clarity. Sorry for the VERY slow response. ;)
